---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cifjdtkaobir/public_html/
    - /bin/cp /css $DEPLOYPATH
    - /bin/cp /js $DEPLOYPATH
    - /bin/cp /img $DEPLOYPATH
    - /bin/cp /fontawesome $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp login.html $DEPLOYPATH
    - /bin/cp signup.html $DEPLOYPATH
    - /bin/cp forgot-password.html $DEPLOYPATH
    - /bin/cp reset-password.html $DEPLOYPATH