---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cifjdtkaobir/public_html/
    - /bin/cp -R public/css $DEPLOYPATH
    - /bin/cp -R public/fontawesome $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH
    - /bin/cp -R public/img $DEPLOYPATH