# Generated by Django 3.0.8 on 2020-09-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200913_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(help_text='add country codes like +234', max_length=15, unique=True),
        ),
    ]
