# Generated by Django 3.0.8 on 2020-09-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200921_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='example@nextbrain.io', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(help_text='+234 9033295156', max_length=15, unique=True),
        ),
    ]
